name: generic-file-adapter
services:
  generic-adapter:
    image: telicent/generic-file-adapter:0.2.0
    restart: no
    volumes:
      - type: bind
        # Source is the local file path which you want to mount into the container
        # this is where you data files and config files can go
        source: ./data
        # Target is where the folder is being mounted
        # This is the folder the python should look at for config and the data files
        target: /app/adapter/data
        read_only: true
    environment:
      - BOOTSTRAP_SERVERS=host.docker.internal:9092
      - PRODUCER_NAME=generic-file-adapter
      - SOURCE_NAME=local-files
      - CONTENT_TYPE=text/turtle
      - TARGET_TOPIC=knowledge
      - DEFAULT_LABEL=*
